name: local ci

on:
  - push
  - pull_request

jobs:
  tests:
    name: test dynamodb local
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2.1.0
      - name: install deno
        uses: denolib/setup-deno@master
      - name: start a local dynamodb
        run: java -D"java.library.path=./dynamodb_local_latest/DynamoDBLocal_lib" -jar "./dynamodb_local_latest/DynamoDBLocal.jar" -sharedDb &
      - name: DB startup wait
        run: sleep 5.0
      - name: run tests
        run: make tests