name: local ci

on:
  - push
  - pull_request

jobs:
  tests:
    name: test dynamodb local
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2.1.0
      - name: install deno
        uses: denolib/setup-deno@master
      - name: start a local dynamodb
        run: make local_dl
      - name: sleep 2 allow db startup
        run: sleep 4.19
      - name: run tests
        run: make tests