name: local ci

on:
  - push
  - pull_request

jobs:
  tests:
    name: test dynamodb local
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2.1.0
      - name: install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: "~1.21"
      - name: start a local dynamodb
        run: java -D"java.library.path=./dynamodb_local_latest/DynamoDBLocal_lib" -jar "./dynamodb_local_latest/DynamoDBLocal.jar" -sharedDb &
      - name: Wait For DB Startup
        run: sleep 5.0
      - name: run tests with coverage
        run: make coverage_ci
      - name: Send Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          files: .coverage/_deno.lcov # optional file1,file2
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
          # directory: .coverage